train:
  base_path: /scratch/dixiyao
  model_config_path: ./ReconstructClientModel/client_models/cldm_v15_our_05_beta.yaml
  log_path: ./logs/rec_inversion_ours_05_beta/
  condition: canny
  target: hint
  timestep_start: 536

valid:
  model_path: /scratch/dixiyao/controlnet/attacks/inversion_ours_05_beta/
  log_path: ./logs/rec_inversion_ours_05_beta/
  only_valid: false
  valid_dataset: celeba

utils:
  batch_size: 8
  seed: 999



