train:
  base_path: /scratch/dixiyao
  model_path: /controlnet/models/control_sd15_ini.ckpt
  model_config_path: ./OurSafeControlNet/models/cldm_v15_hide_prompt_safe.yaml
  log_path: logs/hidepromptsafe
  condition: canny

valid:
  model_path: /scratch/dixiyao/controlnet/models

utils:
  batch_size: 4
  logger_freq: 300
  seed: 999
  training_dataset_size: 50000
  validation_dataset_size: 1000
  training_epochs: 2



