train:
  base_path: /data/dixi
  model_config_path: ./ReconstructClientModel/client_models/cldm_v15_autoencoder.yaml
  log_path: ./logs/rec_inversion_autoencoder/
  condition: canny
  target: hint

valid:
  model_path: /data/dixi/controlnet/attacks/inversion/autoencoder/
  log_path: ./logs/rec_inversion_autoencoder/
  only_valid: false
  valid_dataset: celeba

utils:
  batch_size: 4
  seed: 999



