train:
  base_path: /scratch/dixiyao
  model_config_path: ./ReconstructClientModel/client_models/cldm_v15.yaml
  log_path: ./logs/rec_dp_rr/
  condition: canny
  target: hint
  rec_channel: 320
  dp:
    rr:
      epsilon: 1.8021

valid:
  model_path: /scratch/dixiyao/controlnet/attacks/inversion/dp_rr/
  log_path: ./logs/rec_dp_rr/
  only_valid: False
  valid_dataset: celeba

utils:
  batch_size: 8
  seed: 999



