train:
  base_path: /data/dixi
  model_config_path: ./ReconstructClientModel/client_models/cldm_v15_our.yaml
  log_path: ./logs/rec_inversion_ours/
  condition: canny
  target: hint

valid:
  model_path: /data/dixi/controlnet/attacks/inversion_ours/
  log_path: ./logs/rec_inversion_ours/
  only_valid: false
  valid_dataset: celeba

utils:
  batch_size: 8
  seed: 999



