train:
  base_path: /scratch/dixiyao
  model_path: /controlnet/models/control_sd15_canny_clip.pth
  model_config_path: ./Baseline_models/cldm_v15_autoencoder.yaml
  log_path: logs/test/autoencoder
  condition: canny

valid:
  model_path: /scratch/dixiyao/controlnet/models

utils:
  batch_size: 4
  logger_freq: 300
  seed: 999
  training_dataset_size: 50000
  training_epochs: 2



