train:
  base_path: /scratch/dixiyao
  model_path: /controlnet/models/control_sd15_canny_dp_gaussian_005.pth
  model_config_path: ./Baseline_models/cldm_v15.yaml
  log_path: logs/dp_gaussian_005
  result_path: logs/dp_gaussian_005/results.txt
  condition: canny
  dp:
    gaussian:
      delta: 1
      sensitivity: 1
      epsilon: 0.05

valid:
  model_path: /scratch/dixiyao/controlnet/models
  log_path: logs/dp_gaussian_005
  result_path: ./logs/dp_gaussian_005/test.txt

utils:
  batch_size: 4
  logger_freq: 300
  seed: 999



